const envVars = {
  HYGRAPH_URL: process.env.NEXT_PUBLIC_HYGRAPH_URL,
  HYGRAPH_TOKEN: process.env.NEXT_PUBLIC_HYGRAPH_TOKEN,
  MAPBOX_API_KEY: process.env.NEXT_PUBLIC_MAPBOX_API_KEY,
  MAPBOX_USER_ID: process.env.NEXT_PUBLIC_MAPBOX_USER_ID,
  MAPBOX_STYLE_ID: process.env.NEXT_PUBLIC_MAPBOX_STYLE_ID
};

export default envVars;
